// JavaScript Document
document.writeln("<style>");
document.writeln("*{ margin:0; padding:0}");
document.writeln(".yb_conct{position:fixed;z-index:9999999;top:200px;right:-127px;cursor:pointer;transition:all .3s ease}");
document.writeln(".yb_bar ul li{width:180px;height:53px;font:16px/53px \'Microsoft YaHei\';color:#fff;text-indent:54px;margin-bottom:3px;border-radius:3px;transition:all .5s ease;overflow:hidden}");
document.writeln(".yb_bar .yb_top{background:#ff4a00 url(http://www.qingshumlt.com/images/fixCont.png) no-repeat 0 0}");
document.writeln(".yb_bar .yb_phone{background:#ff4a00 url(http://www.qingshumlt.com/images/fixCont.png) no-repeat 0 -113px}");
document.writeln(".yb_bar .yb_money{background:#ff4a00 url(http://www.qingshumlt.com/images/fixCont.png) no-repeat 0 -57px}");
document.writeln(".yb_bar .yb_QQ{text-indent:0;background:#ff4a00 url(http://www.qingshumlt.com/images/fixCont.png) no-repeat 0 -169px}");
document.writeln(".yb_bar .yb_ercode{background:#ff4a00 url(http://www.qingshumlt.com/images/fixCont.png) no-repeat 0 -226px}");
document.writeln(".hd_qr{padding:0 29px 25px 29px}");
document.writeln(".yb_QQ a{display:block;text-indent:54px;width:100%;height:100%;color:#fff}");
document.writeln("</style>");
document.writeln("<script>");
document.writeln("$(function() {");
document.writeln("	// 悬浮窗口");
document.writeln("	$(\'.yb_conct\').hover(function() {");
document.writeln("		$(\'.yb_conct\').css(\'right\', \'5px\');");
document.writeln("		$(\'.yb_bar .yb_ercode\').css(\'height\', \'200px\');");
document.writeln("	}, function() {");
document.writeln("		$(\'.yb_conct\').css(\'right\', \'-127px\');");
document.writeln("		$(\'.yb_bar .yb_ercode\').css(\'height\', \'53px\');");
document.writeln("	});");
document.writeln("	// 返回顶部");
document.writeln("	$(\'.yb_top\').click(function() {");
document.writeln("		$(\'html,body\').animate({");
document.writeln("			\'scrollTop\': \'0px\'");
document.writeln("		}, 300)");
document.writeln("	});");
document.writeln("});");
document.writeln("</script>");
document.writeln("<div class=\'yb_conct\'>");
document.writeln("  <div class=\'yb_bar\'>");
document.writeln("    <ul>");
document.writeln("      <li class=\'yb_top\'>返回顶部</li>");
document.writeln("      <li class=\'yb_phone\'>400-1080-899</li>");
document.writeln("      <a target=\'_blank\' href=\'http://www.qingshumlt.com/lianxi/\'><li class=\'yb_money\'>加盟费</li></a>");
document.writeln("      <li class=\'yb_QQ\'>");
document.writeln("      	<a target=\'_blank\' href=\'http://p.qiao.baidu.com/cps/chat?siteId=13133871&userId=26679451&cp=&cr=http://www.qingshumlt.com%3Fzhuanyuan0307'>在线咨询</a>");
document.writeln("      </li>");
document.writeln("      <li class=\'yb_ercode\' style=\'height:53px;\'>微信二维码 <br>");
document.writeln("        <img class=\'hd_qr\' src=\'http://www.qingshumlt.com/images/weixin.jpg\' width=\'125\'> </li>");
document.writeln("    </ul>");
document.writeln("  </div>");
document.writeln("</div>");
document.writeln("");